[versions]
compileSdk = "34"
minSdk = "21"
targetSdk = "34"

coreKtx = "1.13.1"
appcompat = "1.7.0"
activityKtx = "1.9.1"
room = '2.6.1'
agp = '8.5.2'
androidTools = "31.5.2"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.29"
about = "10.9.2"

coroutinesAndroid = "1.9.0"
serializationJson = "1.7.3"
material = "1.12.0"

accompanist = "0.33.0-alpha"
composeBom = "2024.06.00"
lifecyle = "2.8.4"
reorderable = "0.9.6"
constraintlayoutCompose = "1.0.1"
navigationCompose = "2.7.7"
dataSaver = "v1.1.5"
sheet = "0.5.4"

okio = "3.3.0"
okhttp = "4.11.0"
net = "3.7.0"
ktor-server = "3.0.3"

recyclerview = "1.3.2"
codeEditor = "0.21.1"
markwon = "4.6.2"
androidsgv = "1.4"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
hutool = "5.8.35"
media = "1.4.0"
caffeine = "3.1.8"
desugar = "2.1.4"
splitties = "3.0.0"

rhino = "1.8.0"
kotlinParcelize = "2.0.20-Beta1"
logging = "7.0.0"
slf4j = "2.0.16"
logback = "1.5.7"
logback-android = "3.0.0"
kotlin-result = "2.0.1"

[libraries]
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
activityKtx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomTesting = { module = "androidx.room:room-testing", version.ref = "room" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-nativation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-webview = { module = "com.google.accompanist:accompanist-webview", version.ref = "accompanist" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

material = { module = "com.google.android.material:material", version.ref = "material" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-image = { module = "io.noties.markwon:image", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }

android-svg = { module = "com.caverock:androidsvg", version.ref = "androidsgv" }


compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-android = { module = "androidx.compose.ui:ui-android" }

compose-material3-core = { module = "androidx.compose.material3:material3" }
compose-material3-winsize = { module = "androidx.compose.material3:material3-window-size-class" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }

lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecyle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecyle" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecyle" }

activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityKtx" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

compose-reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
compose-datasaver = { module = "com.github.FunnySaltyFish.ComposeDataSaver:data-saver", version.ref = "dataSaver" }
compose-sheet = { module = "io.github.dokar3:sheets-m3", version.ref = "sheet" }

about = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about" }
about-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "about" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
net = { module = "com.github.liangjingkanji:Net", version.ref = "net" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor-server" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor-server" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor-server" }
ktor-server-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor-server" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor-server" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor-server" }

code-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "codeEditor" }
code-editor-textmate = { module = "io.github.Rosemoe.sora-editor:language-textmate", version.ref = "codeEditor" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
hutool-crypto = { module = "cn.hutool:hutool-crypto", version.ref = "hutool" }
hutool-cache = { module = "cn.hutool:hutool-cache", version.ref = "hutool" }
splitties-appctx = { module = "com.louiscad.splitties:splitties-appctx", version.ref = "splitties" }
splitties-systemservices = { module = "com.louiscad.splitties:splitties-systemservices", version.ref = "splitties" }

#media = { module = "androidx.media3:media3", version.ref = "media" }
media3-exo = { module = "androidx.media3:media3-exoplayer", version.ref = "media" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "logging" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logback-android" }

mozilla-rhino = { module = "org.mozilla:rhino", version.ref = "rhino" }

# logic-build
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-result = { group = "com.michael-bull.kotlin-result", name = "kotlin-result", version.ref = "kotlin-result" }

[bundles]
andorid-base = ["coreKtx", "appcompat"]
room = ["roomRuntime", "roomKtx"]
accompanist = ["accompanist-systemuicontroller", "accompanist-nativation-animation", "accompanist-webview", "accompanist-permissions"]
lifecycle = ["lifecycle-runtime-compose", "lifecycle-viewmodel-ktx", "lifecycle-livedata-ktx"]
compose = [
    "compose-foundation", "compose-ui",
    "activity-compose", "constraintlayout-compose", "navigation-compose",
    "compose-reorderable", "compose-datasaver", "compose-sheet"
]
compose-material3 = ["compose-material-icons-core", "compose-material-icons-extended", "compose-material3-winsize", "compose-material3-core"]
about = ["about", "about-compose"]
network = ["okio", "okhttp", "net"]
ktor = ["ktor-server-netty", "ktor-server-core", "ktor-server-content-negotiation", "ktor-server-serialization-json", "ktor-server-cors", "ktor-server-status-pages"]
ui = ["material", "recyclerview"]
codeEditor = ["code-editor", "code-editor-textmate"]
markwon = ["markwon-core", "markwon-image", "markwon-linkify", "android-svg"]
media3 = ["media3-exo", "media3-ui"]


[plugins]
application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
about = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about" }
androidApplication = { id = "com.github.jing332.android.application", version = "unspecified" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }